/// Official whitelist of recognized task blocks in Automa Ecosystem (from shared.js tasks dictionary)
pub const AUTOMA_KNOWN_BLOCK_LABELS: &[&str] = &[
    "trigger",
    "ai-workflow",
    "execute-workflow",
    "active-tab",
    "new-tab",
    "open-url",
    "switch-tab",
    "new-window",
    "proxy",
    "go-back",
    "forward-page",
    "close-tab",
    "take-screenshot",
    "browser-event",
    "event-click",
    "click-element",
    "delay",
    "get-text",
    "export-data",
    "element-scroll",
    "link",
    "attribute-value",
    "forms",
    "repeat-task",
    "javascript-code",
    "trigger-event",
    "google-sheets",
    "google-sheets-drive",
    "google-drive",
    "conditions",
    "element-exists",
    "webhook",
    "while-loop",
    "loop-data",
    "loop-elements",
    "loop-breakpoint",
    "blocks-group",
    "blocks-group-2",
    "clipboard",
    "insert-data",
    "switch-to",
    "switch-frame",
    "upload-file",
    "hover-element",
    "save-assets",
    "press-key",
    "handle-dialog",
    "handle-download",
    "reload-tab",
    "delete-data",
    "wait-connections",
    "notification",
    "log-data",
    "tab-url",
    "slice-variable",
    "increase-variable",
    "regex-variable",
    "data-mapping",
    "sort-data",
    "create-element",
    "cookie",
    "block-package",
    "note",
    "workflow-state",
    "parameter-prompt",
    "telegram",
    "email",
];

/// Official VueFlow Component Types supported by automa-webe / automa-vsce canvas
pub const AUTOMA_KNOWN_NODE_TYPES: &[&str] = &[
    "BlockBasic",
    "BlockDelay",
    "BlockConditions",
    "BlockElementExists",
    "BlockBasicWithFallback",
    "BlockRepeatTask",
    "BlockLoopBreakpoint",
    "BlockGroup",
    "BlockGroup2",
    "BlockNote",
    "BlockPackage",
    "BlockTrigger",
];

/// Blocks that are strictly forbidden from having onError fallback connections (shared.js excludeOnError)
pub const EXCLUDE_ON_ERROR: &[&str] = &[
    "note",
    "delay",
    "webhook",
    "trigger",
    "while-loop",
    "conditions",
    "blocks-group",
    "block-package",
    "element-exists",
];

/// Blocks that are strictly forbidden from being nested inside blocks-group (shared.js excludeGroupBlocks)
pub const EXCLUDE_GROUP_BLOCKS: &[&str] = &[
    "trigger",
    "repeat-task",
    "loop-data",
    "loop-breakpoint",
    "blocks-group",
    "conditions",
    "webhook",
    "element-exists",
    "while-loop",
    "block-package",
];

/// Valid comparison operator types supported by Automa ConditionBuilder (shared.js conditionBuilder.compareTypes)
pub const VALID_COMPARE_TYPES: &[&str] = &[
    "eq", "eqi", "nq", "gt", "gte", "lt", "lte", "cnt", "cni", "nct", "nci", "stw", "enw", "rgx",
    "itr", "ifl",
];

/// Supported Proxy Protocols for Virtual Browsers
pub const VALID_PROXY_PROTOCOLS: &[&str] = &["http", "https", "socks4", "socks5"];
